version: '3.8'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
        - ./postgres:/var/lib/postgresql/data
    scheduler:
        image: apache/airflow:1.10.15-python3.8
        command: scheduler
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ../cj-airflow-dags:/home/airflow/cj-airflow-dags
            - ./logs:/opt/airflow/logs
    webserver:
        image: apache/airflow:1.10.15-python3.8
        command: webserver
        entrypoint: ./scripts/entrypoint.sh
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ../cj-airflow-dags:/home/airflow/cj-airflow-dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3